object Versions {
    val kotlin = "1.2.51"
    val support_lib = "27.1.1"
    val lifecycle = "1.1.1"
    val room = "1.1.1"
    val okhttp = "3.11.0"
    val retrofit = "2.4.0"
    val moshi = "1.6.0"
    val picasso = "2.5.2"
    val hyperion = "0.9.24"
}

object Libs {
    val support_v4 = "com.android.support:support-v4:${Versions.support_lib}"
    val support_appcompat_v7 = "com.android.support:appcompat-v7:${Versions.support_lib}"
    val support_recyclerview_v7 = "com.android.support:recyclerview-v7:${Versions.support_lib}"
    val support_design = "com.android.support:design:${Versions.support_lib}"
    val support_constraint_layout = "com.android.support.constraint:constraint-layout:1.1.2"
    val databinding = "com.android.databinding:compiler:3.0.1"
    val lifecycle_extensions = "android.arch.lifecycle:extensions:${Versions.lifecycle}"
    val lifecycle_runtime = "android.arch.lifecycle:runtime:${Versions.lifecycle}"
    val lifecycle_compiler = "android.arch.lifecycle:compiler:${Versions.lifecycle}"
    val lifecycle_common = "android.arch.lifecycle:common-java8:${Versions.lifecycle}"
    val room_runtime = "android.arch.persistence.room:runtime:${Versions.room}"
    val room_compiler = "android.arch.persistence.room:compiler:${Versions.room}"
    val okhttp3 = "com.squareup.okhttp3:okhttp:${Versions.okhttp}"
    val okhttp3_logging_interceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttp}"
    val retrofit2 = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    val retrofit2_converter_moshi = "com.squareup.retrofit2:converter-moshi:${Versions.retrofit}"
    val moshi = "com.squareup.moshi:moshi:${Versions.moshi}"
    val moshi_kotlin = "com.squareup.moshi:moshi-kotlin:${Versions.moshi}"
    val picasso = "com.squareup.picasso:picasso:${Versions.picasso}"
    val kotlin_stdlib = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin}"
    val junit = "junit:junit:4.12"
    val test_runner = "com.android.support.test:runner:1.0.2"
    val espresso_core = "com.android.support.test.espresso:espresso-core:3.0.2"
    val hyperion_core = "com.willowtreeapps.hyperion:hyperion-core:${Versions.hyperion}"
    val hyperion_attr = "com.willowtreeapps.hyperion:hyperion-attr:${Versions.hyperion}"
    val hyperion_measurement = "com.willowtreeapps.hyperion:hyperion-measurement:${Versions.hyperion}"
    val hyperion_disk = "com.willowtreeapps.hyperion:hyperion-disk:${Versions.hyperion}"
    val hyperion_recorder = "com.willowtreeapps.hyperion:hyperion-recorder:${Versions.hyperion}"
    val hyperion_phoenix = "com.willowtreeapps.hyperion:hyperion-phoenix:${Versions.hyperion}"
    val hyperion_crash = "com.willowtreeapps.hyperion:hyperion-crash:${Versions.hyperion}"
    val hyperion_shared_preferences = "com.willowtreeapps.hyperion:hyperion-shared-preferences:${Versions.hyperion}"
    val hyperion_geiger_counter = "com.willowtreeapps.hyperion:hyperion-geiger-counter:${Versions.hyperion}"
    val hyperion_timber = "com.willowtreeapps.hyperion:hyperion-timber:${Versions.hyperion}"
    val hyperion_build_config = "com.willowtreeapps.hyperion:hyperion-build-config:${Versions.hyperion}"
}